### ISSUE TITLE
AI Test: Todo, misc

### ISSUE THREAD

**Issue by Zerahan** [Zerahan/TheMess#1]
- [ ] Ensure existing classes are multiplayer compatible.
- [x] StatusComponent_Basic
    - [ ] handles health changes from damage
    - [ ] needs to be generic enough to handle other stuff like stamina.
- [ ] StatusInterface
    - [ ] Hooks the StatusComponent into the attached actor
- [ ] WorkableComponent_Basic
    - Used by the AI to determine what can be done with the attached actor.
- [ ] Add GAS to project; applying work to a building is an ability.
- [x] Fix day/night cycle
- [ ] Population consumes food at end of shift.
- [x] User can place buildings
- [x] The AI updates work assignments when buildings are placed
- [ ] The user can destroy buildings
- [ ] The AI updates work assignments when buildings are destroyed
- [x] FactionHandlerComponents are added to the GameState for faction-related functions and data.
- [x] FactionHandlerComponent is accessed with faction ID or controller
- [x] FactionHandlerComponent stores food and population information within a UFactionData class that is only created on-demand.
- [ ] 0-2 New units are added every dawn.
- [ ] Watchtower building searches for and attacks hostile units (use EQS?)
- [ ] Watchtower: if no target, each applied work does a scan of the area for targets.
- [ ] Watchtower: if has target, each applied work does [50] damage to target.
- [ ] Rebind faction IDs to team IDs, so they can also be used for AI perception.
- [ ] Make UFactionData into an abstract parent class for UColonyFactionData and UZombieFactionData. (What would a zombie faction actually do? Leave empty for now...)
- Note: Find a way to replicate some data to specific clients instead of entire server. Maybe include a FactionData variant on client PlayerControllers? See: UReplicationGraph for a more advanced method.
- [ ] Add walls once zombies attack blocking structures.

**Comment by Zerahan** [comment]
- [ ] game over if all survivors are killed.
- [ ] survivors can hide in some buildings until the building has been damaged enough to enter destroyed state
- [ ] when a building reaches 0hp, it is converted to ruins that requires resources to reconstruct. 
- [ ] A portion of the resources used to construct a building are added to the ruins build inventory.

**Comment by Zerahan** [comment]
- [ ] game over if all survivors are killed.
- [ ] survivors can hide in some buildings until the building has been damaged enough to enter destroyed state
- [ ] when a building reaches 0hp, it is converted to ruins that requires resources to reconstruct. 
- [ ] A portion of the resources used to construct a building are added to the ruins build inventory.
- GAS abilities:
- [ ] Repair
- [ ] Harvest (subset of withdraw)

**Comment by Zerahan** [comment]
- [ ] game over if all survivors are killed.
- [ ] survivors can hide in some buildings until the building has been damaged enough to enter destroyed state
- [ ] when a building reaches 0hp, it is converted to ruins that requires resources to reconstruct. 
- [ ] A portion of the resources used to construct a building are added to the ruins build inventory.
- GAS abilities:
- [ ] Repair
- [ ] Harvest (subset of withdraw)

**Comment by Zerahan** [comment]
AI test: Work Tasks
- [ ] Repair: go to (garage/house), perform pickup ability, go to damaged structure, perform repair ability
- [ ] Harvest: go to (farm), perform Harvest ability, go to house, perform Dropoff ability
